import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';

const courierNew = localFont({
  src: [{ path: '../public/fonts/Courier-New-Bold.ttf' }, { path: '../public/fonts/Courier-New-Regular.ttf' }],
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru" className={courierNew.className}>
      <body>{children}</body>
    </html>
  );
}
